# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-07-12 13:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.ManyToManyField(related_name='image_no', to=settings.AUTH_USER_MODEL),
        ),
    ]
